import { Page } from '../models/page.model';

export const MOCK_PAGES: Page[] = [
  {
    id: 'p1',
    scanId: 's1',
    path: '/login',
    url: 'https://corp-fin-01.internal/login',
    title: 'Secure Sign In • Finance Portal',
    authState: 'Public',
    riskLevel: 'Critical',
    formsCount: 2,
    buttonsCount: 4,
    linksCount: 6,
    requestsCount: 9,
    loadTimeMs: 812,
    discoveredAt: '2026-07-07 08:13'
  },
  {
    id: 'p2',
    scanId: 's1',
    path: '/accounts/transfer',
    url: 'https://corp-fin-01.internal/accounts/transfer',
    title: 'Funds Transfer • Finance Portal',
    authState: 'Authenticated',
    riskLevel: 'High',
    formsCount: 1,
    buttonsCount: 3,
    linksCount: 4,
    requestsCount: 14,
    loadTimeMs: 968,
    discoveredAt: '2026-07-07 08:15'
  },

  {
    id: 'p3',
    scanId: 's2',
    path: '/sso/callback',
    url: 'https://aad-prod.internal/sso/callback',
    title: 'SSO Callback Handler',
    authState: 'Public',
    riskLevel: 'Medium',
    formsCount: 0,
    buttonsCount: 1,
    linksCount: 2,
    requestsCount: 6,
    loadTimeMs: 540,
    discoveredAt: '2026-07-07 09:41'
  },
  {
    id: 'p4',
    scanId: 's2',
    path: '/admin/users',
    url: 'https://aad-prod.internal/admin/users',
    title: 'Identity Admin Console',
    authState: 'Admin',
    riskLevel: 'High',
    formsCount: 3,
    buttonsCount: 8,
    linksCount: 12,
    requestsCount: 21,
    loadTimeMs: 1120,
    discoveredAt: '2026-07-07 09:44'
  },

  {
    id: 'p5',
    scanId: 's3',
    path: '/console/buckets',
    url: 'https://aws-prod-2.internal/console/buckets',
    title: 'Storage Console',
    authState: 'Authenticated',
    riskLevel: 'High',
    formsCount: 1,
    buttonsCount: 5,
    linksCount: 9,
    requestsCount: 17,
    loadTimeMs: 880,
    discoveredAt: '2026-07-07 09:21'
  },
  {
    id: 'p6',
    scanId: 's3',
    path: '/console/iam',
    url: 'https://aws-prod-2.internal/console/iam',
    title: 'IAM Policy Editor',
    authState: 'Admin',
    riskLevel: 'Medium',
    formsCount: 2,
    buttonsCount: 6,
    linksCount: 7,
    requestsCount: 13,
    loadTimeMs: 705,
    discoveredAt: '2026-07-07 09:24'
  },

  {
    id: 'p7',
    scanId: 's4',
    path: '/account/profile',
    url: 'https://portal.globex-retail.com/account/profile',
    title: 'My Account • Customer Portal',
    authState: 'Authenticated',
    riskLevel: 'Medium',
    formsCount: 2,
    buttonsCount: 5,
    linksCount: 8,
    requestsCount: 11,
    loadTimeMs: 690,
    discoveredAt: '2026-07-06 11:06'
  },
  {
    id: 'p8',
    scanId: 's4',
    path: '/orders/history',
    url: 'https://portal.globex-retail.com/orders/history',
    title: 'Order History',
    authState: 'Authenticated',
    riskLevel: 'Low',
    formsCount: 1,
    buttonsCount: 3,
    linksCount: 15,
    requestsCount: 8,
    loadTimeMs: 615,
    discoveredAt: '2026-07-06 11:09'
  },

  {
    id: 'p9',
    scanId: 's5',
    path: '/gateway/docs',
    url: 'https://api-gateway.partners.internal/gateway/docs',
    title: 'API Gateway Documentation',
    authState: 'Public',
    riskLevel: 'Low',
    formsCount: 0,
    buttonsCount: 2,
    linksCount: 20,
    requestsCount: 5,
    loadTimeMs: 430,
    discoveredAt: '2026-07-05 14:31'
  },
  {
    id: 'p10',
    scanId: 's5',
    path: '/gateway/keys',
    url: 'https://api-gateway.partners.internal/gateway/keys',
    title: 'API Key Management',
    authState: 'Authenticated',
    riskLevel: 'High',
    formsCount: 1,
    buttonsCount: 4,
    linksCount: 3,
    requestsCount: 12,
    loadTimeMs: 760,
    discoveredAt: '2026-07-05 14:34'
  },

  {
    id: 'p11',
    scanId: 's6',
    path: '/payslips',
    url: 'https://hr-ess.internal/payslips',
    title: 'Payslip Viewer',
    authState: 'Authenticated',
    riskLevel: 'Medium',
    formsCount: 1,
    buttonsCount: 2,
    linksCount: 5,
    requestsCount: 7,
    loadTimeMs: 590,
    discoveredAt: '2026-07-06 16:03'
  },
  {
    id: 'p12',
    scanId: 's6',
    path: '/benefits/enrollment',
    url: 'https://hr-ess.internal/benefits/enrollment',
    title: 'Benefits Enrollment',
    authState: 'Authenticated',
    riskLevel: 'Low',
    formsCount: 3,
    buttonsCount: 6,
    linksCount: 4,
    requestsCount: 9,
    loadTimeMs: 640,
    discoveredAt: '2026-07-06 16:05'
  },

  {
    id: 'p13',
    scanId: 's7',
    path: '/support/chat',
    url: 'https://mbanking-api.internal/support/chat',
    title: 'Support Chat • Mobile Banking',
    authState: 'Authenticated',
    riskLevel: 'Medium',
    formsCount: 1,
    buttonsCount: 3,
    linksCount: 2,
    requestsCount: 10,
    loadTimeMs: 520,
    discoveredAt: '2026-07-04 07:56'
  },
  {
    id: 'p14',
    scanId: 's7',
    path: '/transactions/export',
    url: 'https://mbanking-api.internal/transactions/export',
    title: 'Transaction Export',
    authState: 'Authenticated',
    riskLevel: 'Critical',
    formsCount: 1,
    buttonsCount: 2,
    linksCount: 3,
    requestsCount: 6,
    loadTimeMs: 480,
    discoveredAt: '2026-07-04 07:59'
  },

  {
    id: 'p15',
    scanId: 's8',
    path: '/onboarding/kyc',
    url: 'https://vendor-onboarding.internal/onboarding/kyc',
    title: 'KYC Verification',
    authState: 'Authenticated',
    riskLevel: 'High',
    formsCount: 4,
    buttonsCount: 5,
    linksCount: 3,
    requestsCount: 15,
    loadTimeMs: 910,
    discoveredAt: '2026-07-07 12:00'
  },
  {
    id: 'p16',
    scanId: 's8',
    path: '/onboarding/contracts',
    url: 'https://vendor-onboarding.internal/onboarding/contracts',
    title: 'Contract Upload',
    authState: 'Authenticated',
    riskLevel: 'Medium',
    formsCount: 2,
    buttonsCount: 3,
    linksCount: 2,
    requestsCount: 8,
    loadTimeMs: 700,
    discoveredAt: '2026-07-07 12:00'
  },

  {
    id: 'p17',
    scanId: 's9',
    path: '/checkout/payment',
    url: 'https://checkout.globex-retail.com/checkout/payment',
    title: 'Payment Step • Checkout',
    authState: 'Public',
    riskLevel: 'Critical',
    formsCount: 2,
    buttonsCount: 3,
    linksCount: 4,
    requestsCount: 19,
    loadTimeMs: 1040,
    discoveredAt: '2026-07-07 10:48'
  },
  {
    id: 'p18',
    scanId: 's9',
    path: '/checkout/confirmation',
    url: 'https://checkout.globex-retail.com/checkout/confirmation',
    title: 'Order Confirmation',
    authState: 'Public',
    riskLevel: 'Low',
    formsCount: 0,
    buttonsCount: 2,
    linksCount: 5,
    requestsCount: 7,
    loadTimeMs: 460,
    discoveredAt: '2026-07-07 10:51'
  },

  {
    id: 'p19',
    scanId: 's10',
    path: '/wiki/search',
    url: 'https://wiki.internal/wiki/search',
    title: 'Wiki Search',
    authState: 'Public',
    riskLevel: 'Low',
    formsCount: 1,
    buttonsCount: 2,
    linksCount: 30,
    requestsCount: 6,
    loadTimeMs: 390,
    discoveredAt: '2026-07-03 18:23'
  },
  {
    id: 'p20',
    scanId: 's10',
    path: '/wiki/admin',
    url: 'https://wiki.internal/wiki/admin',
    title: 'Wiki Admin Panel',
    authState: 'Admin',
    riskLevel: 'High',
    formsCount: 2,
    buttonsCount: 5,
    linksCount: 8,
    requestsCount: 11,
    loadTimeMs: 730,
    discoveredAt: '2026-07-03 18:26'
  }
];
